{
 "title": "Pizza Dashboard 2.0",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(requests{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(method) (rate(requests_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\"}[$__interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(endpoint) (rate(requests_total{source=\"jwt-pizza-service\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "active_users_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(cpu_percent)", "legendFormat": "CPU" },
    {
     "expr": "avg(memory_percent{source=\"jwt-pizza-service\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Auth Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "rate(auth_attempts_total{source=\"jwt-pizza-service\"}[$__interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizza_total{source=\"jwt-pizza-service\"}[$__interval])",
     "legendFormat": "Pizzas sold ({{status}})"
    },
    {
     "expr": "rate(purchase_total{source=\"jwt-pizza-service\"}[$__interval])",
     "legendFormat": "Purchases ({{status}})"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "revenue_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Revenue"
    }
   ]
  }
 ]
}